### ISSUE TITLE
提问：登录问题

### ISSUE THREAD

**Issue by admin-ulala** [FirmianaMarsili/picacomic-api#1]
我这边使用python按您的代码实现了一下，已经能获取到正确的签名，但仍然无法登录。提示的报错是超时报错。

**Comment by FirmianaMarsili** [comment]
贴一下代码 我看一下

**Comment by admin-ulala** [comment]
环境是 windows10 + python 3.8


下面是代码
![源码](https://user-images.githubusercontent.com/58620182/156185434-42220083-6559-43a0-b6ea-26b53f0b5d6b.png)


下面是控制台输出以及报错信息
![输出](https://user-images.githubusercontent.com/58620182/156184791-4ba8a0f0-825a-408b-a4e1-34f56adcfcba.png)

**Comment by FirmianaMarsili** [comment]
有开启代理吗 这个是需要代理才可以正常访问的

**Comment by admin-ulala** [comment]
昨天的时候用了翻墙，我的代码也是不行的。就是报错换成了代理的 no such xxxx什么的
但是github上另一个pc端的pica项目是可以登录的。

**Comment by FirmianaMarsili** [comment]
这种报错一般不是pica自己返回的错误，而是自己本地网路的问题。你可以在测试前用当前网络打开我的测试代码登录一下，如果可以登录成功再进行测试一下你的代码，看看返回什么错误
