### ISSUE TITLE
请教：请问这些API是如何提取的呢？

### ISSUE THREAD

**Issue by banmao999** [FirmianaMarsili/picacomic-api#3]
你好，我曾尝试过提取Pica的API，用过两种方式，但是最后都放弃了
1、使用Fiddler抓取手机APP的请求——但是因为访问pica需要VPN，而使用VPN后Fiddler就不能抓取到请求
2、拆包APK，提取源代码，然而经过编译优化的代码反编译后非常难啃，因此放弃
想请教你，这些API和逻辑是怎么获取到的呢？

另外，非常感谢你的API 🚀👍👍👍👍

**Comment by FirmianaMarsili** [comment]
![1](https://github.com/FirmianaMarsili/picacomic-api/assets/35676922/3efaeeec-8e62-4c4f-8c27-435fa3c61f53)
啊这

**Comment by FirmianaMarsili** [comment]
现在应该有多种方式，我之前在telegram中看到好像有网页端，你可以在网页中分析。
另外手机端你可以使用Stream，百度设置教程以后，你就可以得到这样的数据，这样你可以得到哪条协议需要传什么参数。
![2](https://github.com/FirmianaMarsili/picacomic-api/assets/35676922/dd263a45-eb79-47b6-8928-829370ebc666)
![3](https://github.com/FirmianaMarsili/picacomic-api/assets/35676922/75d26e44-32ef-4956-a3e4-5bbcf2f02b34)
